//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.05 at 09:55:36 PM IST 
//


package com.husky.mock.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Party"/>
 *         &lt;element ref="{}Service"/>
 *         &lt;element ref="{}ChannelName"/>
 *         &lt;element ref="{}ChannelID"/>
 *         &lt;element ref="{}ActivationState"/>
 *         &lt;element ref="{}ChannelState" minOccurs="0"/>
 *         &lt;element ref="{}ShortLog" minOccurs="0"/>
 *         &lt;element ref="{}UpdateState" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "party",
    "service",
    "channelName",
    "channelID",
    "activationState",
    "channelState",
    "shortLog",
    "updateState"
})
@XmlRootElement(name = "Channel")
public class Channel {
	public Channel(){
		
	}
	

    @XmlElement(name = "Party", required = true)
    protected String party;
    @XmlElement(name = "Service", required = true)
    protected String service;
    @XmlElement(name = "ChannelName", required = true)
    protected String channelName;
    @XmlElement(name = "ChannelID", required = true)
    protected String channelID;
    @XmlElement(name = "ActivationState", required = true)
    protected String activationState;
    @XmlElement(name = "ChannelState")
    protected String channelState;
    @XmlElement(name = "ShortLog")
    protected String shortLog;
    @XmlElement(name = "UpdateState")
    protected String updateState;

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParty(String value) {
        this.party = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the channelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * Sets the value of the channelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelName(String value) {
        this.channelName = value;
    }

    /**
     * Gets the value of the channelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelID() {
        return channelID;
    }

    /**
     * Sets the value of the channelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelID(String value) {
        this.channelID = value;
    }

    /**
     * Gets the value of the activationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationState() {
        return activationState;
    }

    /**
     * Sets the value of the activationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationState(String value) {
        this.activationState = value;
    }

    /**
     * Gets the value of the channelState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelState() {
        return channelState;
    }

    /**
     * Sets the value of the channelState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelState(String value) {
        this.channelState = value;
    }

    /**
     * Gets the value of the shortLog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortLog() {
        return shortLog;
    }

    /**
     * Sets the value of the shortLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortLog(String value) {
        this.shortLog = value;
    }

	public String getUpdateState() {
		return updateState;
	}

	public void setUpdateState(String updateState) {
		this.updateState = updateState;
	}
    
    

}
